/twist_mux:
  ros__parameters:
    topics:
      joy:
        topic   : joy_cmd_vel
        timeout : 0.5
        priority: 10
      drone:
        topic   : drone_cmd_vel
        timeout : 0.5
        priority: 15
    locks:
      e_stop:
        topic   : e_stop
        timeout : 0.0
        priority: 255